tools:
  php_analyzer:
    enabled: true
    filter:
      excluded_paths: 
        - spec/*
  php_pdepend:
    enabled: true
    filter:
      exclude_paths:
        - spec/*
  php_code_sniffer: true
  php_cs_fixer: true
